dist: precise
sudo: required
language: node_js
node_js:
  - stable
script:
  - yarn test
install: true

cache:
  directories:
    - node_modules

deploy:
  provider: heroku
  api_key:
    secure: N/93bS2qg/NJ9QG4MWsWz9KctTxrgLSwJaCZz8bBhJKVzzUEqEo5iaZb4OA/pAkjZvnR0cfLzxCAYuVbs8G464ByEFjxzBl0ikbElZhfd7kPjAIWR8RQNK4sgK1MvFRghHalc6svK6WMb/Y/WECs/skT8PtGsJKiJCKZwBk4GjtPAaFvz8B2SQA9AQLSYVmYM69lakG9mmsLWmGtH9ARXCurFLJCf/QA9kV7wthk7JfjQAbooxz3+A23Iimm8G/URoYLIo9Qyw1ijeckmro2AfEohDceQaQJv19K+6V2bF6PkEiDzbMRiShrP1KBkUkRWWM/r/+71Ylhr9ZRgyV1j+msBGsTBR2i9Sdz6Fhm6ABL5z5NfoQI7J9+bEoLUQgQkjyUGxEe+0Z6FOGvaal7wYLg6VZ0gQHpeurrbHL4seWzuRyAEXnDu4ZKOtA2j1xAFPXOlUgS4wHoeg4rvd2KOQGmr52IxNSQGm5a47A4qGJLxc1z3seFzEH/Yc0mRkV0xWwoGUWqqqE7MSN/TJxiQhQXmY66GRT0c4aXKRdKp+1GH7cPNPRQ/aZ2YtHP6llUaqHKybSP3+P3a0WAswIre+WU35wJ6irVVNR6B11K5kSFYD0YQtvOq9LWANP1EZYeXN4RhaPFlh7WLwqdQAYusCllzIbnzeFStWAl4V6sf2w=
  app: Q-Learning-React
  on:
    repo: spprichard/Q-Learning-React
