dist: precise
sudo: required
language: node_js
node_js:
- stable
script:
- yarn test
install: true
cache:
  directories:
    - node_modules
deploy:
  provider: heroku
  api_key:
    secure: BsKSI1gEsFKYPA85WDlpdLWqS2o7Wys34myjWMxmT+ZZeFmuE9YQGp2titam3fdpnn642ErSSdb1qYxkrCzS6v/rigHR+SK4Bh6T71jN47o9nUIpxtTei1vljtEAeu+mv/u5jhKcMgEdsU5eemph19O84qJl8kskidW0osrIO/HjNkFYKqt7Sh5vb121tAU47B2JY8F9DuQool7n7t6WmjZupK6REB4oQY9gLefS7qUtms0A2SVt9ttGvtFFhqTeRfGgdjeJwqPqZ8HgVOqmAo657mn59Vr5Z9O781F5rsufHwUVWOejl9l79LnCxmwWhfiGwJOeXhxtUEgBMWM2YxUfNr5DWoB6itj7oRcD4lKg21prRhD8Cfwi5ua2lap9ioD2WpyVzSghuqa3FjwoshdL6/DHFZhf+9CvKNSyhuTtBRLzZ4GBy8y8g+ZICvyqSHGWw0MeMdBvEsfKB6z2wtAI8P6oByuYWEgzFnztpCtMJfW/h23uWh/vXdIKVxq69Vme5KsGoqSE809KtbMKqghIUROhoW85Fj3xRPylf5Ktu84pqbtfbShfivtxqThVG3WoPyTebMNvP0xzywOxePztykA3/gky2fZo6L+/QNBQxCtfwXsjBLRVLCtIC9lI5kI+NYstX8Iew+nilLRSuPS9Ze/Wl53+eX4/pz3vCKg=
  app: qlearner
  on:
    repo: spprichard/Q-Learning-React
