dist: precise
sudo: required
language: node_js
node_js:
- stable
script:
- yarn
- yarn test
install: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: JQ5Gv3ZygDv51pDl6agiHTttckeVFq37yr+he4AZTnpN3kJxDhwOy34+1oYK1zPAnl4AxkbA8/IVV0WyLpzAgyZz7AMsMuwNKNkDu4Ud+9M+RuxEPoDEHBJ5uM2QhfMaQGkO4yPx/BcZn+0dfEk4FtgY2h6dUUynPc8bggke/vZUMpB+LmQDkD8eIkcloderJQTjdn6hZKfTwrHKZEQm1OKdh4aXQkIfMzeHCNIs0F5m9LCgskcXwIHwTqBeQJEgubWeDJ1Z0lXgsEdjop/AlPtcNMGLuiy56rUh4QuZ02yQFsufyVuq9QVB4d4KINcUU1H06VPORpTq9QmMEiUK+sQlQU3h5/vJ+A9wUT2NurESsnMvuTdg0nCDUV58QeWxfrKuHxYvTlkXwKh1TEnPhAAG4j04aozU6AFs6rOMhhz9n/DH0tgiJhGH1BDOAoLBx6BP3OBxTFadwzQP7RGsdDldvfT5W022xQ3kwnQwkq14Z+A0JguDDx2hnNV5kZzMZn00ip6gJ83vAiiHuJbquR/lXNAiiYJrIyuOcMXV6xD2+2BSkmBlDReb4X86r7D50VsQSkfVveuBEothKmzP1l8SlS+0v9nabXHKp54FVScL2cnUTsCpAC/1MKuHwHnTOu7GUVeXg7iU6YpKZebn1p4cWdrk4C3TkPXpla6nRfU=
  app: qlearner
  on:
    repo: spprichard/Q-Learning-React
