dist: precise
language: node_js
node_js:
  - "stable"

  cache:
    directories:
    - node_modules
    - packages/create-react-app/node_modules
    - packages/react-scripts/node_modules

    install: true