dist: precise
sudo: required
language: node_js
node_js:
- stable
script:
- yarn test
install: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: Pz2IKh9hF1GxyFKFLbqSLkM+mrQU13hmfCPBPnDdDkPKMN7eORmqG5jPL+kBsHwxRvVcBCUmwLrqF59WBipq5G7klAZK5gY5OgW1Bsk0ch7WkoWZZUYUvoGB0VwGz73JViE1R1R28/qBxEPQO5wi5ch5ao7vErBkyJKqOBht6bpS21vHaLGJoEysd+pUXPiAEc0VsrSARIxedfHX0pxoEYIOBgAj/wPYlqY+JrPIck9kd3rvlq6d696c9QYIV5VWHf0JBeCS/lk9N0JBHP0aqOcC2F7GSz0cMDSRmKg4q24X7t/9T+qGaRI85YoEP229dxItUHg/f8mmiARU2vY175q6jBZ7wP4FdtRwbbi5w+eE8++Gtn8hJd3zwpcx67YlogDMjL14wyPhRJpzyIzz8n//VWdEGkU79nezk2+xQtGDpDFTQG10Ro6vVwyb2u0Ssd/wpW2WNApxq/4tEWYiNedbgWMBTxDV6E9SLETJRInCt7XVP995TiWfH44U40UGstRL6UBzqiHib0SjptjJ76tTOcQDS2r7roRS0YSo9rjLUL2BG9iwgSvT+W05LOhmtzpczr7DY2WxlHxwbu65WOLFxJEeeKAaTqjPOBJo3tgLjHCuEHUFsVXs9pN6S1PU/Cd6OebAHqbKCfyDbw+C4gRrlY45LU2G6nt27k/WvaI=
  app: qlearner
  on:
    repo: spprichard/Q-Learning-React
