dist: precise
language: node_js

cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
install: true

env:
  global:
    - USE_YARN=no
