dist: precise
sudo: required
language: node_js
node_js:
- stable
script:
- yarn
- yarn test
install: true
cache:
  directories:
  - node_modules
deploy:
  provider: heroku
  api_key:
    secure: i+bG1ier7O1knVIcCZ8rjWbd2WPwRvtXi92ccpAf3hnlplQQUzObpIraZrCqtVfYQQYvoXzbrtpkI7qU2uQkh5TOPJyHcOi3xVB08X6swu5mmjFg++0vDMF8xfx4CcHsH9x8qEsVYRyBUUY5nYj/JFQsdHwDS2EfUSIu7BwyqW8IGwGqHktqaIHYZbE2Zxscfk2ezTMoR3jMe1f9xWXF12oAw+mYn+6tvrIo3VCBl6vAnU9LiaIvNupAD0Km+dIMWi7QHVeWhSNS05GczDoBRoOt862EIyfZvRs9orDFjRtS+Gwh8c2xV1l3g5Ifv2OfGQQYvdOLsHW/URaznY4BzyK4NjDpbV55fctidul5gYFFws4EEEaqkmQy2GDa+WDc+fhrIAtSqvM7pp1Wht+lF0tJtPBN7qg5BAo6Zdwg6DIoWKWs9qlXjLVpAOeOtsNvlJRPf08FPgfg7Lll8+jBBzSyROTjzrVpWTHbq3FgvJ9JsYzQy4+3pT9QgQEDZK6CT+tbJS+lTG7RXV5dK6VIqPScqqV0tsChNHNxM/479ha/jyrtoePMQmy1n34+pbIKWJusk7KXuLok7UGTgC4/gp6LEHYdmEAxO+D/tTwtMNaITc6PjveRX7JXZDA/Z2HAFvduLGKDdVhY8i2TZyvrUjZbVPja7leH6KDA35Wkvkk=
  app: qlearner
  on:
    repo: spprichard/Q-Learning-React
